### PR TITLE
added support for Raspberry Pi and later snowflake proxy versions

### PR DESCRIPTION
**Pull request by hbrns**
changed the echo command to be fully qualified
changed the awk script to look for throughput instead of traffic to fix "error: unknown unit were".
changed uname argument to be more portable

### CODE REVIEW

**Comment by cristianrz** [comment]
* Fine for the `uname`
* `/usr/bin` doesn't hurt but just curious: did you run into any problems by not having it?
* Can you expand on this `"error: unknown unit were"`?

**Comment by hbrns** [comment]
I build the standalone snowflake proxy, and it logs the following
https://gitweb.torproject.org/pluggable-transports/snowflake.git/tree/proxy/lib/pt_event_logger.go#n42
          p.logger.Printf("In the last %v, there were %v connections. Traffic Relayed ↑ %v %v, ↓ %v %v.\n",

Now the awk script hits because of this /Traffic/ and $8 is the word "were", which convbyte() does not recognize as a unit, so it panics. 

As the lines piconyx is interested in are something like this
    2022/03/12 10:00:12 Traffic throughput (up|down): 145 KB|6 KB -- (52 OnMessages, 1252 Sends, over 1290 seconds)
but not like this
   2022/03/12 09:25:35 In the last 1h0m0s, there were 4 connections. Traffic Relayed ↑ 188 MB, ↓ 21 MB.

I am proposing to change /Traffic/ to /throughput/.

**Comment by hbrns** [comment]
as to /usr/bin/echo vs echo
The Ubuntu bash has a builtin echo and that does not understand -e so it echos it instead

piconyx-echo

**Comment by cristianrz** [comment]
LGTM

**Pull request merged**
